import { jsPDF } from "jspdf";
import type { CollectionEntry } from "../types";
import { formatCurrency } from "./calculations";
import { formatDateForDisplay, getDateRangeLabel } from "./date";

const COMPANY_NAME = "OPTIFIRST TZ LIMITED";

export interface PaperReportTotals {
  cashSales?: number;
  creditSales?: number;
  totalAmount?: number;
  mismatchCount?: number;
  creditTotal?: number;
}

export interface PaperReportPdfOptions {
  title: string;
  startDate?: string;
  endDate?: string;
  monthLabel?: string;
  shopName?: string;
  inchargeName?: string;
  employeeName?: string;
  generatedBy?: string;
  headers: string[];
  rows: Array<Array<string | number>>;
  filename: string;
  totals?: PaperReportTotals;
  orientation?: "portrait" | "landscape";
}

function renderHeader(doc: jsPDF, options: PaperReportPdfOptions) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(COMPANY_NAME, 14, 16);

  doc.setFontSize(12);
  doc.setTextColor(37, 99, 235);
  doc.text(options.title, 14, 24);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`${options.monthLabel ? "Month" : "Date"}: ${options.monthLabel || getDateRangeLabel(options.startDate, options.endDate)}`, 14, 31);
  doc.text(`Shop: ${options.shopName || "All Shops"}`, 14, 36);
  doc.text(`Incharge: ${options.inchargeName || "-"}`, 14, 41);
  doc.text(`Generated by: ${options.generatedBy || options.employeeName || "System"}`, 14, 46);
  doc.text(`Generated time: ${new Date().toLocaleString("en-TZ")}`, 14, 51);

  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setDrawColor(203, 213, 225);
  doc.line(14, 55, pageWidth - 14, 55);
}

function renderTotals(doc: jsPDF, y: number, totals?: PaperReportTotals): number {
  if (!totals) return y;

  const pageWidth = doc.internal.pageSize.getWidth();
  const boxX = pageWidth - 92;
  const currentY = y + 4;

  doc.setDrawColor(203, 213, 225);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(boxX, currentY, 78, 32, 2, 2, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  doc.text("Totals", boxX + 4, currentY + 6);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  const lines: string[] = [];
  if (totals.cashSales !== undefined) lines.push(`Cash Sales: ${formatCurrency(totals.cashSales)}`);
  if (totals.creditSales !== undefined) lines.push(`Credit Sales: ${formatCurrency(totals.creditSales)}`);
  if (totals.creditTotal !== undefined) lines.push(`Credit Total: ${formatCurrency(totals.creditTotal)}`);
  if (totals.totalAmount !== undefined) lines.push(`Total Amount: ${formatCurrency(totals.totalAmount)}`);
  if (totals.mismatchCount !== undefined) lines.push(`Stock Mismatch Count: ${totals.mismatchCount}`);

  lines.slice(0, 4).forEach((line, index) => {
    doc.text(line, boxX + 4, currentY + 13 + index * 5);
  });

  return currentY + 40;
}

function renderSignatureSection(doc: jsPDF, y: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const left = 14;
  const right = pageWidth - 14;
  const sectionY = y + 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text("Prepared By", left, sectionY);
  doc.text("Checked By", left + 70, sectionY);
  doc.text("Approved By", right - 70, sectionY);

  doc.setDrawColor(148, 163, 184);
  doc.line(left, sectionY + 14, left + 45, sectionY + 14);
  doc.line(left + 70, sectionY + 14, left + 115, sectionY + 14);
  doc.line(right - 70, sectionY + 14, right - 25, sectionY + 14);

  return sectionY + 22;
}

export function exportPaperReportToPdf(options: PaperReportPdfOptions) {
  const doc = new jsPDF({
    orientation: options.orientation || "landscape",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const left = 14;
  const right = pageWidth - 14;
  const tableWidth = right - left;
  const colWidth = tableWidth / options.headers.length;
  let y = 62;

  renderHeader(doc, options);

  const drawTableHeader = () => {
    doc.setFillColor(241, 245, 249);
    doc.setDrawColor(203, 213, 225);
    doc.rect(left, y - 5, tableWidth, 8, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    options.headers.forEach((header, index) => {
      doc.text(String(header), left + index * colWidth + 1.5, y);
    });
    y += 8;
  };

  drawTableHeader();

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(30, 41, 59);

  options.rows.forEach((row) => {
    if (y > pageHeight - 34) {
      doc.addPage();
      renderHeader(doc, options);
      y = 62;
      drawTableHeader();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(30, 41, 59);
    }

    doc.setDrawColor(226, 232, 240);
    doc.line(left, y + 2, right, y + 2);
    row.forEach((cell, index) => {
      const value = cell === undefined || cell === null ? "" : String(cell);
      const maxChars = Math.max(5, Math.floor(colWidth / 1.45));
      const clipped = value.length > maxChars ? `${value.slice(0, maxChars - 2)}..` : value;
      doc.text(clipped, left + index * colWidth + 1.5, y);
    });
    y += 7;
  });

  y = renderTotals(doc, y, options.totals);
  if (y > pageHeight - 28) {
    doc.addPage();
    renderHeader(doc, options);
    y = 62;
  }
  renderSignatureSection(doc, y);

  doc.save(`${options.filename}.pdf`);
}

export function exportToPdf(
  title: string,
  headers: string[],
  rows: Array<Array<string | number>>,
  filename: string
) {
  exportPaperReportToPdf({
    title,
    headers,
    rows,
    filename,
    orientation: "landscape"
  });
}

export interface PdfTableSection {
  title: string;
  headers: string[];
  rows: Array<Array<string | number>>;
}

export function exportSectionsToPdf(options: {
  title: string;
  filename: string;
  startDate?: string;
  endDate?: string;
  generatedBy?: string;
  sections: PdfTableSection[];
}) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const left = 14;
  const right = pageWidth - 14;
  let y = 16;

  const renderPageHeader = () => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(15, 23, 42);
    doc.text(COMPANY_NAME, left, 14);
    doc.setFontSize(11);
    doc.setTextColor(37, 99, 235);
    doc.text(options.title, left, 22);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(`Date: ${getDateRangeLabel(options.startDate, options.endDate)}`, left, 29);
    doc.text(`Generated by: ${options.generatedBy || "System"}`, left, 34);
    doc.line(left, 38, right, 38);
    y = 46;
  };

  const ensureSpace = (height: number) => {
    if (y + height <= pageHeight - 14) return;
    doc.addPage();
    renderPageHeader();
  };

  renderPageHeader();

  options.sections.forEach((section) => {
    if (section.rows.length === 0) return;
    ensureSpace(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(`${section.title} (${section.rows.length})`, left, y);
    y += 6;

    const tableWidth = right - left;
    const colWidth = tableWidth / section.headers.length;
    doc.setFillColor(241, 245, 249);
    doc.setDrawColor(203, 213, 225);
    doc.rect(left, y - 4.5, tableWidth, 7.5, "FD");
    doc.setFontSize(7);
    section.headers.forEach((header, index) => {
      doc.text(header, left + index * colWidth + 1.2, y);
    });
    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.7);
    section.rows.forEach((row) => {
      ensureSpace(7);
      doc.setDrawColor(226, 232, 240);
      doc.line(left, y + 2, right, y + 2);
      row.forEach((cell, index) => {
        const value = String(cell ?? "");
        const maxChars = Math.max(5, Math.floor(colWidth / 1.35));
        const clipped = value.length > maxChars ? `${value.slice(0, maxChars - 2)}..` : value;
        doc.text(clipped, left + index * colWidth + 1.2, y);
      });
      y += 6;
    });
    y += 7;
  });

  doc.save(`${options.filename}.pdf`);
}

export function generateMonthlyCollectionPdf(
  collectionRows: CollectionEntry[],
  shop: string,
  month: string,
  options: { inchargeName?: string; generatedBy?: string } = {}
) {
  const totals = collectionRows.reduce(
    (sum, row) => ({
      cashSales: sum.cashSales + Number(row.CashSales || 0),
      creditSales: sum.creditSales + Number(row.CreditSales || 0),
      totalSales: sum.totalSales + Number(row.TotalSales || 0),
      depositCash: sum.depositCash + Number(row.DepositCash || 0),
      depositLIPA: sum.depositLIPA + Number(row.DepositLIPA || 0),
      variance: sum.variance + Number(row.Variance || 0),
      depositInBank: sum.depositInBank + Number(row.DepositInBank || 0),
      salesVsEFD: sum.salesVsEFD + Number(row.SalesVsEFD || 0)
    }),
    { cashSales: 0, creditSales: 0, totalSales: 0, depositCash: 0, depositLIPA: 0, variance: 0, depositInBank: 0, salesVsEFD: 0 }
  );

  exportPaperReportToPdf({
    title: "Daily Sales and Collection Report",
    monthLabel: month,
    shopName: shop,
    inchargeName: options.inchargeName,
    generatedBy: options.generatedBy,
    filename: `Monthly_Collection_${shop.replace(/\s+/g, "_")}_${month}`,
    headers: [
      "Sl.No",
      "Date",
      "Day",
      "Cash sales(A)",
      "Credit sales(B)",
      "Total Sales C=(A+B)",
      "Cash Deposit",
      "LIPA",
      "Variance",
      "Deposit in Bank",
      "Date of Deposit",
      "EFD Z Report",
      "Sales vs EFD",
      "Name",
      "Signature"
    ],
    rows: [
      ...collectionRows.map((row, index) => [
        index + 1,
        formatDateForDisplay(row.Date),
        row.Day,
        formatCurrency(row.CashSales),
        formatCurrency(row.CreditSales),
        formatCurrency(row.TotalSales),
        formatCurrency(row.DepositCash),
        formatCurrency(row.DepositLIPA),
        formatCurrency(row.Variance),
        formatCurrency(row.DepositInBank),
        row.DateOfDeposit ? formatDateForDisplay(row.DateOfDeposit) : "-",
        formatCurrency(row.EFDZReport),
        formatCurrency(row.SalesVsEFD),
        row.Name || "-",
        row.Signature || "-"
      ]),
      [
        "Total",
        "",
        "",
        formatCurrency(totals.cashSales),
        formatCurrency(totals.creditSales),
        formatCurrency(totals.totalSales),
        formatCurrency(totals.depositCash),
        formatCurrency(totals.depositLIPA),
        formatCurrency(totals.variance),
        formatCurrency(totals.depositInBank),
        "",
        "",
        formatCurrency(totals.salesVsEFD),
        "",
        ""
      ]
    ],
    orientation: "landscape"
  });
}
